version: '3.8'

services:
  order_service:
    build: .
    container_name: "orders_microservice"
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DBHOST=
      - DBUSER=
      - DBPASSWORD=
      - USERS_ADDRESSES_URL=
      - FLASK_APP=application
