version: '3.8'

services:
  order_service:
    build: .
    container_name: "orders_microservice"
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    environment:
      - DBHOST=host
      - DBUSER=user
      - DBPASSWORD=password
      - FLASK_APP=application
