version: '3.8'

services:
  order_service:
    build: .
    container_name: "orders_microservice"
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=host
      - DB_USER=user
      - DB_PASSWORD=password
      - FLASK_APP=application
