version: '3.8'

services:
  order_service:
    build: .
    container_name: "orders_microservice"
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DBHOST=database-2.clbmc2tqyqce.us-east-2.rds.amazonaws.com
      - DBUSER=admin
      - DBPASSWORD=seadogs!
      - FLASK_APP=application
